# Generated by Django 4.0.3 on 2022-03-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('personal_details', models.CharField(max_length=300)),
                ('occupational_details', models.CharField(max_length=300)),
                ('cibil', models.IntegerField()),
                ('is_loan_sanctioned', models.BooleanField(default=False, verbose_name='Sanctioned')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_amt', models.FloatField()),
                ('is_loan_details_filled', models.BooleanField(default=False, verbose_name='Yes')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='Operational_Head.customer')),
            ],
        ),
    ]
