# Generated by Django 4.0.3 on 2022-03-14 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/')),
                ('sigh', models.ImageField(upload_to='img/')),
                ('pan', models.ImageField(upload_to='img/')),
                ('aadhar', models.ImageField(upload_to='img/')),
                ('bank', models.ImageField(upload_to='img/')),
                ('check1', models.ImageField(upload_to='img/')),
                ('salary', models.ImageField(upload_to='img/')),
                ('itr', models.FileField(upload_to='img/')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseInformatin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Father_Name', models.CharField(max_length=100)),
                ('Current_Address', models.CharField(max_length=100)),
                ('Parmanet_Address', models.CharField(max_length=100)),
                ('Pin_Code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('Annual_Income', models.FloatField()),
                ('Income_certificat_number', models.CharField(max_length=100)),
                ('Product_ID', models.CharField(max_length=100)),
                ('Vehicle_Manufacturer', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('Vehicle_Color', models.CharField(max_length=100)),
                ('Required_Loan_Amount', models.FloatField()),
                ('Guarantor_Name', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
                ('Contact_Number', models.IntegerField()),
                ('Aadhar_Number', models.IntegerField()),
                ('Pan_Card_Number', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Holder_Name', models.CharField(max_length=100)),
                ('Account_Number', models.IntegerField()),
                ('Bank_Name', models.CharField(max_length=100)),
                ('IFSC_Code', models.CharField(max_length=100)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
