# Generated by Django 4.0.3 on 2022-03-15 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Enquiry_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Amount', models.FloatField()),
                ('Tenure_of_Loan', models.IntegerField()),
                ('Purpose_of_Loan', models.TextField()),
                ('Pancard_No', models.CharField(max_length=50)),
                ('Mobile_No', models.IntegerField()),
                ('loan_status', models.BooleanField(default=False, verbose_name='Approved')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
