# Generated by Django 4.0.3 on 2022-03-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_Head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_head',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
